Repository zwave-js/zwave-js, pull requests merged in 2021-01, with the labels that each got.

#1272 fix: initialize transports after importing log/shared
  packages/core/src/log/shared.ts
Labels: bug

#1271 feat(ci): auto-release nightly versions of @zwave-js/config
  .actrc
  .github/workflows/nightly-config-publish.yml
Labels: infrastructure

#1262 fix: delete "keep until next" nonces AFTER the next one was received
  packages/core/src/security/Manager.test.ts
  packages/core/src/security/Manager.ts
  packages/zwave-js/src/lib/commandclass/SecurityCC.ts
  packages/zwave-js/src/lib/node/Node.ts
Labels: device compatibility

#1285 chore(ci): enforce semantic PR titles
  .github/semantic.yml
  CONTRIBUTING.md
Labels: infrastructure

#1286 feat(ci): create publish action to release PR test builds
  .github/actions/zwave-js-bot/action.yml
  .github/actions/zwave-js-bot/main.js
  .github/workflows/zwave-js-bot.yml
  .gitignore
  .prettierignore
Labels: infrastructure

#1297 feat(ci): split lint step into eslint/wotan and own zwave linters
  .github/workflows/test-and-release.yml
Labels: infrastructure

#1491 fix(ci): display filename before annotation to get around GH hiding it
  maintenance/tools.ts
Labels: infrastructure

#1516 fix: correctly implement Z-Wave+ Role Type Specs for interview procedure
  docs/development/config-files.md
  maintenance/schemas/device-config.json
  packages/config/config/devices/0x0373/id-150_0.0-1.5.json
  packages/config/config/devices/0x0373/id-150_1.6.json
  packages/config/config/devices/0x0373/id-150_compat.json
  packages/config/src/CompatConfig.ts
  packages/config/src/ConfigManager.ts
  packages/core/src/security/Manager.test.ts
  packages/core/src/security/Manager.ts
  packages/zwave-js/src/lib/commandclass/SecurityCC.ts
  packages/zwave-js/src/lib/commandclass/ZWavePlusCC.ts
  packages/zwave-js/src/lib/controller/Controller.ts
  packages/zwave-js/src/lib/node/Node.ts
Labels: verified ✔

#1522 fix: treat no error as successful command, update currentValue immediately
  packages/zwave-js/src/lib/commandclass/API.ts
  packages/zwave-js/src/lib/commandclass/BasicCC.ts
  packages/zwave-js/src/lib/commandclass/BinarySwitchCC.ts
  packages/zwave-js/src/lib/commandclass/CentralSceneCC.ts
  packages/zwave-js/src/lib/commandclass/ClimateControlScheduleCC.ts
  packages/zwave-js/src/lib/commandclass/ClockCC.ts
  packages/zwave-js/src/lib/commandclass/ColorSwitchCC.ts
  packages/zwave-js/src/lib/commandclass/ConfigurationCC.ts
  packages/zwave-js/src/lib/commandclass/DoorLockCC.ts
  packages/zwave-js/src/lib/commandclass/IndicatorCC.ts
  packages/zwave-js/src/lib/commandclass/LanguageCC.ts
  packages/zwave-js/src/lib/commandclass/LockCC.ts
  packages/zwave-js/src/lib/commandclass/ManufacturerProprietaryCC.ts
  packages/zwave-js/src/lib/commandclass/MultilevelSwitchCC.ts
  packages/zwave-js/src/lib/commandclass/NodeNamingCC.ts
  packages/zwave-js/src/lib/commandclass/ProtectionCC.ts
  packages/zwave-js/src/lib/commandclass/SoundSwitchCC.ts
  packages/zwave-js/src/lib/commandclass/ThermostatModeCC.ts
  packages/zwave-js/src/lib/commandclass/ThermostatSetbackCC.ts
  packages/zwave-js/src/lib/commandclass/ThermostatSetpointCC.ts
  packages/zwave-js/src/lib/commandclass/TimeCC.ts
  packages/zwave-js/src/lib/commandclass/TimeParametersCC.ts
  packages/zwave-js/src/lib/commandclass/UserCodeCC.ts
  packages/zwave-js/src/lib/commandclass/WakeUpCC.ts
  packages/zwave-js/src/lib/node/Node.ts
Labels: verified ✔

#1534 feat(bot): auto-label config PRs
  .github/workflows/zwave-js-bot_pulls.yml
Labels: infrastructure

#1523 feat(config): add support for philio pat02-a flood sensor
  packages/config/config/devices/0x013c/pat02-a.json
Labels: config ⚙

#1540 fix(config): force Wake Up as supported for Aeon Labs Minimote
  packages/config/config/devices/0x0086/dsa03202.json
Labels: config ⚙
